-- =====================================================================
-- PORTAL UNIVERSITARIO UTSC · Script 01: ESQUEMA  (versión PostgreSQL / SUPABASE)
-- Pegar COMPLETO en Supabase → SQL Editor → New query → RUN.
-- Convertido desde MySQL 8: misma estructura y mismas reglas de negocio.
-- =====================================================================
-- IMPORTANTE: borra y vuelve a crear el esquema utsc_portal (si ya existía,
-- se pierden sus datos). No toca el esquema "public" de Supabase.
-- =====================================================================

DROP SCHEMA IF EXISTS utsc_portal CASCADE;
CREATE SCHEMA utsc_portal;
SET search_path TO utsc_portal, public;

-- =====================================================================
-- BLOQUE 0 · Función genérica para updated_at
-- (reemplaza el "ON UPDATE CURRENT_TIMESTAMP" de MySQL)
-- =====================================================================
CREATE FUNCTION fn_set_updated_at() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- =====================================================================
-- BLOQUE 1 · Catálogos académicos y usuarios
-- =====================================================================
CREATE TABLE carreras (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave            VARCHAR(5)   NOT NULL UNIQUE,
  nombre           VARCHAR(100) NOT NULL UNIQUE,
  creditos_totales SMALLINT     NOT NULL DEFAULT 120 CHECK (creditos_totales > 0)
);

CREATE TABLE periodos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR(30) NOT NULL UNIQUE,
  fecha_inicio DATE        NOT NULL,
  fecha_fin    DATE        NOT NULL,
  es_actual    BOOLEAN     NOT NULL DEFAULT FALSE,
  CONSTRAINT chk_periodo_fechas CHECK (fecha_fin > fecha_inicio)
);
-- Solo un periodo puede ser "actual" (en MySQL era la columna virtual actual_unico)
CREATE UNIQUE INDEX uq_periodo_actual ON periodos (es_actual) WHERE es_actual;

CREATE TABLE usuarios (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correo        VARCHAR(120) NOT NULL UNIQUE,
  password_hash CHAR(60)     NOT NULL,
  rol           TEXT         NOT NULL CHECK (rol IN ('alumno','docente','admin')),
  nombre        VARCHAR(60)  NOT NULL,
  apellido_paterno VARCHAR(60) NOT NULL,
  apellido_materno VARCHAR(60),
  telefono      VARCHAR(15),
  sobre_mi      TEXT,
  foto_url      VARCHAR(255),
  activo        BOOLEAN      NOT NULL DEFAULT TRUE,
  ultimo_acceso TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT chk_usuario_correo   CHECK (correo LIKE '%_@utsc.edu.mx'),
  CONSTRAINT chk_usuario_hash     CHECK (password_hash ~ '^\$2[aby]\$[0-9]{2}\$.{53}$'),
  CONSTRAINT chk_usuario_telefono CHECK (telefono IS NULL OR telefono ~ '^[0-9+() -]{8,15}$')
);
CREATE TRIGGER trg_usuarios_updated BEFORE UPDATE ON usuarios
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE ajustes_usuario (
  usuario_id              INTEGER PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,
  notif_blog              BOOLEAN NOT NULL DEFAULT TRUE,
  notif_noticias          BOOLEAN NOT NULL DEFAULT TRUE,
  notif_pagos_tramites    BOOLEAN NOT NULL DEFAULT TRUE,
  notif_correo            BOOLEAN NOT NULL DEFAULT FALSE,
  privacidad_publicaciones TEXT   NOT NULL DEFAULT 'todos'
                          CHECK (privacidad_publicaciones IN ('todos','mi_carrera','solo_yo')),
  mostrar_carrera         BOOLEAN NOT NULL DEFAULT TRUE,
  mostrar_matricula       BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_ajustes_updated BEFORE UPDATE ON ajustes_usuario
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
COMMENT ON TABLE  ajustes_usuario IS 'Preferencias de cada usuario (notificaciones y privacidad)';
COMMENT ON COLUMN ajustes_usuario.notif_blog IS 'Avisar cuando reaccionan o comentan mis publicaciones';
COMMENT ON COLUMN ajustes_usuario.notif_noticias IS 'Avisar de noticias nuevas';
COMMENT ON COLUMN ajustes_usuario.notif_pagos_tramites IS 'Avisar de cargos, pagos y cambios en mis trámites';
COMMENT ON COLUMN ajustes_usuario.notif_correo IS 'Además de la campana, mandar copia por correo';
COMMENT ON COLUMN ajustes_usuario.privacidad_publicaciones IS 'Quién puede ver mis publicaciones';
COMMENT ON COLUMN ajustes_usuario.mostrar_carrera IS 'Mostrar mi carrera en mi perfil';
COMMENT ON COLUMN ajustes_usuario.mostrar_matricula IS 'Mostrar mi matrícula en mi perfil';

CREATE TABLE grupos (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave      VARCHAR(10) NOT NULL,
  carrera_id INTEGER     NOT NULL REFERENCES carreras(id),
  periodo_id INTEGER     NOT NULL REFERENCES periodos(id),
  semestre   SMALLINT    NOT NULL CHECK (semestre BETWEEN 1 AND 12),
  turno      TEXT        NOT NULL CHECK (turno IN ('matutino','vespertino')),
  CONSTRAINT uq_grupo UNIQUE (clave, periodo_id)
);

CREATE TABLE alumnos (
  usuario_id    INTEGER PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,
  matricula     VARCHAR(10) NOT NULL UNIQUE CHECK (matricula ~ '^[0-9]{5,10}$'),
  carrera_id    INTEGER     NOT NULL REFERENCES carreras(id),
  grupo_id      INTEGER     REFERENCES grupos(id),
  fecha_ingreso DATE        NOT NULL,
  estatus       TEXT        NOT NULL DEFAULT 'activo'
                CHECK (estatus IN ('activo','baja_temporal','baja_definitiva','egresado'))
);

CREATE TABLE docentes (
  usuario_id        INTEGER PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,
  numero_empleado   VARCHAR(10) NOT NULL UNIQUE,
  area              VARCHAR(80),
  cubiculo          VARCHAR(60),
  horario_asesoria  VARCHAR(120)
);

CREATE TABLE materias (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave      VARCHAR(10)  NOT NULL UNIQUE,
  nombre     VARCHAR(100) NOT NULL,
  creditos   SMALLINT     NOT NULL CHECK (creditos BETWEEN 1 AND 15),
  carrera_id INTEGER      NOT NULL REFERENCES carreras(id),
  semestre   SMALLINT     NOT NULL CHECK (semestre BETWEEN 1 AND 12),
  CONSTRAINT uq_materia_carrera UNIQUE (carrera_id, nombre)
);

CREATE TABLE docente_materia (
  docente_id INTEGER NOT NULL REFERENCES docentes(usuario_id) ON DELETE CASCADE,
  materia_id INTEGER NOT NULL REFERENCES materias(id)         ON DELETE CASCADE,
  PRIMARY KEY (docente_id, materia_id)
);

CREATE TABLE inscripciones (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id    INTEGER NOT NULL REFERENCES alumnos(usuario_id) ON DELETE CASCADE,
  materia_id   INTEGER NOT NULL REFERENCES materias(id),
  periodo_id   INTEGER NOT NULL REFERENCES periodos(id),
  calificacion NUMERIC(4,2),
  -- columna calculada: NULL = en curso, >= 8 aprobada, si no reprobada
  estado       TEXT GENERATED ALWAYS AS (
                 CASE WHEN calificacion IS NULL THEN 'en_curso'
                      WHEN calificacion >= 8    THEN 'aprobada'
                      ELSE 'reprobada' END) STORED,
  CONSTRAINT chk_calificacion CHECK (calificacion IS NULL OR calificacion BETWEEN 0 AND 10),
  CONSTRAINT uq_inscripcion UNIQUE (alumno_id, materia_id, periodo_id)
);

CREATE TABLE horario_clases (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_id    INTEGER NOT NULL REFERENCES grupos(id)  ON DELETE CASCADE,
  materia_id  INTEGER NOT NULL REFERENCES materias(id),
  docente_id  INTEGER NOT NULL REFERENCES docentes(usuario_id),
  dia         TEXT    NOT NULL CHECK (dia IN ('lunes','martes','miercoles','jueves','viernes','sabado')),
  hora_inicio TIME    NOT NULL,
  hora_fin    TIME    NOT NULL,
  aula        VARCHAR(20),
  CONSTRAINT chk_horas CHECK (hora_fin > hora_inicio),
  CONSTRAINT uq_horario UNIQUE (grupo_id, dia, hora_inicio)
);

-- =====================================================================
-- BLOQUE 2 · Contacto
-- =====================================================================
CREATE TABLE departamentos (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre   VARCHAR(100) NOT NULL UNIQUE,
  correo   VARCHAR(120) NOT NULL UNIQUE CHECK (correo LIKE '%_@utsc.edu.mx'),
  responsable VARCHAR(100),
  ubicacion   VARCHAR(100),
  telefono VARCHAR(12)  CHECK (telefono IS NULL OR telefono ~ '^[0-9]{2}-[0-9]{4}-[0-9]{4}$'),
  horario     VARCHAR(100)
);

-- (Se agregaron las llaves foráneas que en MySQL faltaban)
CREATE TABLE mensajes_contacto (
  folio           VARCHAR(20) PRIMARY KEY DEFAULT '',   -- lo llena el trigger: CTO-AAAA-NNNN
  alumno_id       INTEGER     NOT NULL REFERENCES alumnos(usuario_id) ON DELETE CASCADE,
  departamento_id INTEGER     NOT NULL REFERENCES departamentos(id),
  asunto          VARCHAR(150) NOT NULL,
  mensaje         TEXT         NOT NULL,
  estado          TEXT         NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','respondido')),
  respuesta       TEXT,
  respondido_en   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- =====================================================================
-- BLOQUE 3 · Blog
-- =====================================================================
CREATE TABLE categorias_blog (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE publicaciones (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  autor_id     INTEGER      NOT NULL REFERENCES usuarios(id),
  categoria_id INTEGER      NOT NULL REFERENCES categorias_blog(id),
  titulo       VARCHAR(150) NOT NULL CHECK (char_length(titulo) >= 3),
  contenido    TEXT         NOT NULL,
  imagen_url   VARCHAR(255),
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  deleted_at   TIMESTAMPTZ
);
CREATE INDEX idx_publicaciones_borrado ON publicaciones (deleted_at, created_at);
CREATE TRIGGER trg_publicaciones_updated BEFORE UPDATE ON publicaciones
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE hashtags (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL UNIQUE CHECK (nombre ~ '^[a-z0-9_ñáéíóú]+$')
);

CREATE TABLE publicacion_hashtag (
  publicacion_id INTEGER NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  hashtag_id     INTEGER NOT NULL REFERENCES hashtags(id)      ON DELETE CASCADE,
  PRIMARY KEY (publicacion_id, hashtag_id)
);

CREATE TABLE reacciones (
  publicacion_id INTEGER NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id     INTEGER NOT NULL REFERENCES usuarios(id)      ON DELETE CASCADE,
  tipo           TEXT    NOT NULL DEFAULT 'me_gusta' CHECK (tipo IN ('me_gusta')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (publicacion_id, usuario_id)
);

CREATE TABLE comentarios (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id INTEGER NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id     INTEGER NOT NULL REFERENCES usuarios(id),
  contenido      VARCHAR(1000) NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at     TIMESTAMPTZ
);

CREATE TABLE reportes (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id INTEGER NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id     INTEGER NOT NULL REFERENCES usuarios(id),
  motivo         TEXT    NOT NULL CHECK (motivo IN ('spam','ofensivo','informacion_falsa','inapropiado','otro')),
  detalle        VARCHAR(300),
  estado         TEXT    NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','revisado','descartado')),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_reporte UNIQUE (publicacion_id, usuario_id)
);

-- =====================================================================
-- BLOQUE 4 · Noticias, eventos, avisos, notificaciones
-- =====================================================================
CREATE TABLE categorias_noticia (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE noticias (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id    INTEGER      NOT NULL REFERENCES categorias_noticia(id),
  autor_id        INTEGER      REFERENCES usuarios(id),
  titulo          VARCHAR(150) NOT NULL,
  resumen         VARCHAR(300),
  cuerpo          TEXT         NOT NULL,
  imagen_url      VARCHAR(255),
  destacada       BOOLEAN      NOT NULL DEFAULT FALSE,
  minutos_lectura SMALLINT     NOT NULL DEFAULT 1 CHECK (minutos_lectura BETWEEN 1 AND 60),
  fecha_publicacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Solo una noticia destacada a la vez (en MySQL era destacada_unica)
CREATE UNIQUE INDEX uq_noticia_destacada ON noticias (destacada) WHERE destacada;

CREATE TABLE eventos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo       VARCHAR(150) NOT NULL,
  descripcion  TEXT,
  lugar        VARCHAR(120),
  fecha_inicio TIMESTAMPTZ  NOT NULL,
  fecha_fin    TIMESTAMPTZ,
  departamento_id INTEGER REFERENCES departamentos(id),
  CONSTRAINT chk_evento_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

CREATE TABLE avisos (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo     VARCHAR(150) NOT NULL,
  contenido  TEXT         NOT NULL,
  prioridad  TEXT         NOT NULL DEFAULT 'normal' CHECK (prioridad IN ('normal','importante','urgente')),
  departamento_id INTEGER REFERENCES departamentos(id),
  vigente_desde DATE      NOT NULL DEFAULT CURRENT_DATE,
  vigente_hasta DATE,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE notificaciones (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  modulo     TEXT    NOT NULL CHECK (modulo IN ('blog','noticias','eventos','avisos','pagos','tramites',
                       'biblioteca','driver','horario','calificaciones','contacto','perfil','sistema')),
  titulo     VARCHAR(150) NOT NULL,
  mensaje    VARCHAR(500),
  enlace     VARCHAR(120),
  leida      BOOLEAN NOT NULL DEFAULT FALSE,
  leida_en   TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notif_usuario ON notificaciones (usuario_id, leida, created_at);

CREATE TABLE actividad (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  modulo     VARCHAR(30)  NOT NULL,
  accion     VARCHAR(60)  NOT NULL,
  descripcion VARCHAR(300),
  ip         VARCHAR(45),
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_actividad_usuario ON actividad (usuario_id, created_at);

-- =====================================================================
-- BLOQUE 5 · Trámites y pagos
-- =====================================================================
CREATE TABLE tramites_catalogo (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR(100) NOT NULL UNIQUE,
  descripcion  VARCHAR(300),
  costo        NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (costo >= 0),
  dias_habiles SMALLINT NOT NULL DEFAULT 3 CHECK (dias_habiles > 0),
  requisitos   TEXT,
  activo       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE solicitudes_tramite (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio         VARCHAR(20) NOT NULL DEFAULT '' ,   -- lo llena el trigger: TRM-AAAA-NNNN
  alumno_id     INTEGER NOT NULL REFERENCES alumnos(usuario_id) ON DELETE CASCADE,
  tramite_id    INTEGER NOT NULL REFERENCES tramites_catalogo(id),
  estado        TEXT    NOT NULL DEFAULT 'pendiente'
                CHECK (estado IN ('pendiente','en_proceso','completado','cancelado')),
  observaciones VARCHAR(300),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_solicitud_folio UNIQUE (folio)
);
-- Un alumno no puede tener 2 solicitudes ACTIVAS del mismo trámite
CREATE UNIQUE INDEX uq_tramite_activo ON solicitudes_tramite (alumno_id, tramite_id)
  WHERE estado IN ('pendiente','en_proceso');
CREATE TRIGGER trg_solicitudes_updated BEFORE UPDATE ON solicitudes_tramite
  FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TABLE cargos (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id         INTEGER NOT NULL REFERENCES alumnos(usuario_id) ON DELETE CASCADE,
  concepto          VARCHAR(150) NOT NULL,
  monto             NUMERIC(10,2) NOT NULL CHECK (monto > 0),
  estado            TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','pagado','cancelado')),
  periodo_id        INTEGER REFERENCES periodos(id),
  solicitud_id      INTEGER UNIQUE REFERENCES solicitudes_tramite(id),
  fecha_vencimiento DATE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pagos (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cargo_id         INTEGER NOT NULL REFERENCES cargos(id),
  monto            NUMERIC(10,2) NOT NULL CHECK (monto > 0),
  metodo           TEXT NOT NULL CHECK (metodo IN ('tarjeta','spei','oxxo')),
  referencia       VARCHAR(40) NOT NULL DEFAULT '' UNIQUE,   -- la llena el trigger
  tarjeta_ultimos4 CHAR(4),
  estado           TEXT NOT NULL DEFAULT 'completado' CHECK (estado IN ('pendiente','completado','rechazado')),
  pagado_en        TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_pago_tarjeta CHECK (
    (metodo = 'tarjeta' AND tarjeta_ultimos4 ~ '^[0-9]{4}$')
    OR (metodo <> 'tarjeta' AND tarjeta_ultimos4 IS NULL))
);

-- =====================================================================
-- BLOQUE 6 · Biblioteca
-- =====================================================================
CREATE TABLE categorias_libro (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE libros (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  isbn                   VARCHAR(17) UNIQUE CHECK (isbn ~ '^[0-9X-]{10,17}$'),
  titulo                 VARCHAR(200) NOT NULL,
  autor                  VARCHAR(200) NOT NULL,
  editorial              VARCHAR(80),
  edicion                VARCHAR(30),
  anio                   SMALLINT,
  categoria_id           INTEGER NOT NULL REFERENCES categorias_libro(id),
  ejemplares_totales     SMALLINT NOT NULL CHECK (ejemplares_totales >= 0),
  ejemplares_disponibles SMALLINT NOT NULL,
  CONSTRAINT chk_ejemplares CHECK (ejemplares_disponibles BETWEEN 0 AND ejemplares_totales)
);

CREATE TABLE prestamos (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alumno_id        INTEGER NOT NULL REFERENCES alumnos(usuario_id) ON DELETE CASCADE,
  libro_id         INTEGER NOT NULL REFERENCES libros(id),
  tipo             TEXT NOT NULL DEFAULT 'prestamo' CHECK (tipo IN ('reserva','prestamo')),
  estado           TEXT NOT NULL DEFAULT 'activo'   CHECK (estado IN ('activo','devuelto','cancelado')),
  fecha_inicio     DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_limite     DATE,
  fecha_devolucion DATE,
  renovaciones     SMALLINT NOT NULL DEFAULT 0 CHECK (renovaciones BETWEEN 0 AND 1),
  CONSTRAINT chk_renovar_solo_prestamo CHECK (tipo = 'prestamo' OR renovaciones = 0)
);
-- Un alumno no puede tener el mismo libro activo dos veces
CREATE UNIQUE INDEX uq_prestamo_activo ON prestamos (alumno_id, libro_id) WHERE estado = 'activo';

CREATE TABLE recursos_digitales (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(150) NOT NULL,
  descripcion VARCHAR(300),
  tipo        TEXT NOT NULL CHECK (tipo IN ('base_datos','libros_electronicos','revistas','buscador','video','otro')),
  acceso      TEXT NOT NULL CHECK (acceso IN ('libre','campus','remoto')),
  url         VARCHAR(255) NOT NULL CHECK (url LIKE 'https://%')
);

-- =====================================================================
-- BLOQUE 7 · DriverUTSC
-- =====================================================================
CREATE TABLE rutas_driver (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conductor_id INTEGER NOT NULL REFERENCES alumnos(usuario_id),
  sentido      TEXT    NOT NULL CHECK (sentido IN ('hacia_utsc','desde_utsc')),
  lugar        VARCHAR(120) NOT NULL,
  hora_salida  TIME    NOT NULL,
  asientos     SMALLINT NOT NULL CHECK (asientos BETWEEN 1 AND 4),
  precio       NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (precio BETWEEN 0 AND 100),
  vehiculo     VARCHAR(80) NOT NULL,
  notas        VARCHAR(200),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at   TIMESTAMPTZ
);

CREATE TABLE ruta_dias (
  ruta_id INTEGER NOT NULL REFERENCES rutas_driver(id) ON DELETE CASCADE,
  dia     TEXT    NOT NULL CHECK (dia IN ('lunes','martes','miercoles','jueves','viernes','sabado')),
  PRIMARY KEY (ruta_id, dia)
);

CREATE TABLE reservas_viaje (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruta_id     INTEGER NOT NULL REFERENCES rutas_driver(id) ON DELETE CASCADE,
  pasajero_id INTEGER NOT NULL REFERENCES alumnos(usuario_id) ON DELETE CASCADE,
  estado      TEXT NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa','cancelada')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  cancelada_en TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_reserva_activa ON reservas_viaje (ruta_id, pasajero_id) WHERE estado = 'activa';

-- =====================================================================
-- BLOQUE 8 · Reglas de negocio (funciones + triggers PL/pgSQL)
-- (reemplazan los procedimientos y triggers de MySQL con DELIMITER)
-- =====================================================================

-- ---- 8.1 Validar alumno (antes sp_validar_alumno) -------------------
CREATE FUNCTION fn_validar_alumno(p_usuario INT, p_matricula TEXT, p_carrera INT, p_grupo INT)
RETURNS void LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_rol TEXT; v_correo TEXT; v_carrera_grupo INT;
BEGIN
  SELECT rol, correo INTO v_rol, v_correo FROM usuarios WHERE id = p_usuario;
  IF v_rol IS DISTINCT FROM 'alumno' THEN
    RAISE EXCEPTION 'El usuario % no tiene rol alumno', p_usuario;
  END IF;
  IF v_correo <> p_matricula || '@utsc.edu.mx' THEN
    RAISE EXCEPTION 'El correo del alumno debe ser matricula@utsc.edu.mx (esperado %@utsc.edu.mx)', p_matricula;
  END IF;
  IF p_grupo IS NOT NULL THEN
    SELECT carrera_id INTO v_carrera_grupo FROM grupos WHERE id = p_grupo;
    IF v_carrera_grupo IS DISTINCT FROM p_carrera THEN
      RAISE EXCEPTION 'El grupo no pertenece a la carrera del alumno';
    END IF;
  END IF;
END $$;

-- ---- 8.2 Validar horario (antes sp_validar_horario) -----------------
CREATE FUNCTION fn_validar_horario(p_id INT, p_grupo INT, p_docente INT, p_dia TEXT, p_inicio TIME, p_fin TIME)
RETURNS void LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM horario_clases
             WHERE grupo_id = p_grupo AND dia = p_dia
               AND (p_id IS NULL OR id <> p_id)
               AND hora_inicio < p_fin AND hora_fin > p_inicio) THEN
    RAISE EXCEPTION 'El grupo ya tiene una clase que se empalma en ese horario';
  END IF;
  IF EXISTS (SELECT 1 FROM horario_clases
             WHERE docente_id = p_docente AND dia = p_dia
               AND (p_id IS NULL OR id <> p_id)
               AND hora_inicio < p_fin AND hora_fin > p_inicio) THEN
    RAISE EXCEPTION 'El docente ya tiene una clase que se empalma en ese horario';
  END IF;
END $$;

-- ---- 8.3 Usuarios: crear ajustes por defecto ------------------------
CREATE FUNCTION fn_usuarios_ai() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  INSERT INTO ajustes_usuario (usuario_id) VALUES (NEW.id) ON CONFLICT DO NOTHING;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_usuarios_ai AFTER INSERT ON usuarios
  FOR EACH ROW EXECUTE FUNCTION fn_usuarios_ai();

-- ---- 8.4 Alumnos / docentes ----------------------------------------
CREATE FUNCTION fn_alumnos_valida() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  PERFORM fn_validar_alumno(NEW.usuario_id, NEW.matricula, NEW.carrera_id, NEW.grupo_id);
  RETURN NEW;
END $$;
CREATE TRIGGER trg_alumnos_bi BEFORE INSERT ON alumnos FOR EACH ROW EXECUTE FUNCTION fn_alumnos_valida();
CREATE TRIGGER trg_alumnos_bu BEFORE UPDATE ON alumnos FOR EACH ROW EXECUTE FUNCTION fn_alumnos_valida();

CREATE FUNCTION fn_docentes_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF (SELECT rol FROM usuarios WHERE id = NEW.usuario_id) IS DISTINCT FROM 'docente' THEN
    RAISE EXCEPTION 'El usuario % no tiene rol docente', NEW.usuario_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_docentes_bi BEFORE INSERT ON docentes FOR EACH ROW EXECUTE FUNCTION fn_docentes_bi();

-- ---- 8.5 Horario ----------------------------------------------------
CREATE FUNCTION fn_horario_valida() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  PERFORM fn_validar_horario(CASE WHEN TG_OP = 'UPDATE' THEN NEW.id END,
                             NEW.grupo_id, NEW.docente_id, NEW.dia, NEW.hora_inicio, NEW.hora_fin);
  RETURN NEW;
END $$;
CREATE TRIGGER trg_horario_bi BEFORE INSERT ON horario_clases FOR EACH ROW EXECUTE FUNCTION fn_horario_valida();
CREATE TRIGGER trg_horario_bu BEFORE UPDATE ON horario_clases FOR EACH ROW EXECUTE FUNCTION fn_horario_valida();

-- ---- 8.6 Mensajes de contacto: folio CTO-AAAA-NNNN -------------------
CREATE FUNCTION fn_mensajes_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_sig INT; v_anio TEXT := to_char(now(), 'YYYY');
BEGIN
  IF NEW.folio IS NULL OR NEW.folio = '' THEN
    PERFORM pg_advisory_xact_lock(hashtext('folio_contacto'));
    SELECT COALESCE(MAX(split_part(folio, '-', 3)::int), 0) + 1 INTO v_sig
      FROM mensajes_contacto WHERE folio LIKE 'CTO-' || v_anio || '-%';
    NEW.folio := 'CTO-' || v_anio || '-' || lpad(v_sig::text, 4, '0');
  END IF;
  NEW.created_at := COALESCE(NEW.created_at, now());
  RETURN NEW;
END $$;
CREATE TRIGGER trg_mensajes_bi BEFORE INSERT ON mensajes_contacto
  FOR EACH ROW EXECUTE FUNCTION fn_mensajes_bi();

-- ---- 8.7 Reacciones y comentarios (blog) -----------------------------
CREATE FUNCTION fn_reacciones_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM publicaciones WHERE id = NEW.publicacion_id AND deleted_at IS NOT NULL) THEN
    RAISE EXCEPTION 'No se puede reaccionar a una publicación eliminada';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_reacciones_bi BEFORE INSERT ON reacciones FOR EACH ROW EXECUTE FUNCTION fn_reacciones_bi();

CREATE FUNCTION fn_reacciones_ai() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_autor INT; v_titulo TEXT;
BEGIN
  SELECT autor_id, titulo INTO v_autor, v_titulo FROM publicaciones WHERE id = NEW.publicacion_id;
  IF v_autor <> NEW.usuario_id
     AND COALESCE((SELECT notif_blog FROM ajustes_usuario WHERE usuario_id = v_autor), TRUE) THEN
    INSERT INTO notificaciones (usuario_id, modulo, titulo, mensaje)
    VALUES (v_autor, 'blog', 'Nuevo me gusta', 'A alguien le gustó tu publicación: ' || v_titulo);
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_reacciones_ai AFTER INSERT ON reacciones FOR EACH ROW EXECUTE FUNCTION fn_reacciones_ai();

CREATE FUNCTION fn_comentarios_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM publicaciones WHERE id = NEW.publicacion_id AND deleted_at IS NOT NULL) THEN
    RAISE EXCEPTION 'No se puede comentar una publicación eliminada';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_comentarios_bi BEFORE INSERT ON comentarios FOR EACH ROW EXECUTE FUNCTION fn_comentarios_bi();

CREATE FUNCTION fn_comentarios_ai() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_autor INT; v_titulo TEXT;
BEGIN
  SELECT autor_id, titulo INTO v_autor, v_titulo FROM publicaciones WHERE id = NEW.publicacion_id;
  IF v_autor <> NEW.usuario_id
     AND COALESCE((SELECT notif_blog FROM ajustes_usuario WHERE usuario_id = v_autor), TRUE) THEN
    INSERT INTO notificaciones (usuario_id, modulo, titulo, mensaje)
    VALUES (v_autor, 'blog', 'Nuevo comentario', 'Comentaron tu publicación: ' || v_titulo);
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_comentarios_ai AFTER INSERT ON comentarios FOR EACH ROW EXECUTE FUNCTION fn_comentarios_ai();

-- ---- 8.8 Solicitudes de trámite --------------------------------------
CREATE FUNCTION fn_solicitudes_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_sig INT; v_anio TEXT := to_char(now(), 'YYYY');
BEGIN
  IF NOT EXISTS (SELECT 1 FROM tramites_catalogo WHERE id = NEW.tramite_id AND activo) THEN
    RAISE EXCEPTION 'El trámite no existe o no está activo';
  END IF;
  IF NEW.estado IN ('pendiente','en_proceso') AND EXISTS (
       SELECT 1 FROM solicitudes_tramite
       WHERE alumno_id = NEW.alumno_id AND tramite_id = NEW.tramite_id
         AND estado IN ('pendiente','en_proceso')) THEN
    RAISE EXCEPTION 'Ya tienes una solicitud activa de este trámite';
  END IF;
  IF NEW.folio IS NULL OR NEW.folio = '' THEN
    PERFORM pg_advisory_xact_lock(hashtext('folio_tramite'));
    SELECT COALESCE(MAX(split_part(folio, '-', 3)::int), 0) + 1 INTO v_sig
      FROM solicitudes_tramite WHERE folio LIKE 'TRM-' || v_anio || '-%';
    NEW.folio := 'TRM-' || v_anio || '-' || lpad(v_sig::text, 4, '0');
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_solicitudes_bi BEFORE INSERT ON solicitudes_tramite
  FOR EACH ROW EXECUTE FUNCTION fn_solicitudes_bi();

CREATE FUNCTION fn_solicitudes_ai() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_costo NUMERIC; v_nombre TEXT;
BEGIN
  SELECT costo, nombre INTO v_costo, v_nombre FROM tramites_catalogo WHERE id = NEW.tramite_id;
  IF v_costo > 0 AND NEW.estado <> 'cancelado' THEN
    INSERT INTO cargos (alumno_id, concepto, monto, periodo_id, solicitud_id, fecha_vencimiento)
    VALUES (NEW.alumno_id, 'Trámite: ' || v_nombre, v_costo,
            (SELECT id FROM periodos WHERE es_actual), NEW.id, CURRENT_DATE + 7);
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_solicitudes_ai AFTER INSERT ON solicitudes_tramite
  FOR EACH ROW EXECUTE FUNCTION fn_solicitudes_ai();

CREATE FUNCTION fn_solicitudes_au() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF NEW.estado = 'cancelado' AND OLD.estado <> 'cancelado' THEN
    UPDATE cargos SET estado = 'cancelado'
     WHERE solicitud_id = NEW.id AND estado = 'pendiente';
  END IF;
  IF NEW.estado <> OLD.estado
     AND COALESCE((SELECT notif_pagos_tramites FROM ajustes_usuario WHERE usuario_id = NEW.alumno_id), TRUE) THEN
    INSERT INTO notificaciones (usuario_id, modulo, titulo, mensaje)
    VALUES (NEW.alumno_id, 'tramites', 'Tu trámite cambió de estado',
            'Folio ' || NEW.folio || ': ahora está "' || NEW.estado || '"');
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_solicitudes_au AFTER UPDATE ON solicitudes_tramite
  FOR EACH ROW EXECUTE FUNCTION fn_solicitudes_au();

-- ---- 8.9 Pagos ---------------------------------------------------------
CREATE FUNCTION fn_pagos_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_estado TEXT; v_monto NUMERIC; v_pref TEXT; v_sig INT;
BEGIN
  SELECT estado, monto INTO v_estado, v_monto FROM cargos WHERE id = NEW.cargo_id;
  IF v_estado IS DISTINCT FROM 'pendiente' THEN
    RAISE EXCEPTION 'Solo se pueden pagar cargos pendientes';
  END IF;
  IF NEW.monto <> v_monto THEN
    RAISE EXCEPTION 'El monto del pago (%) no coincide con el del cargo (%)', NEW.monto, v_monto;
  END IF;
  IF NEW.referencia IS NULL OR NEW.referencia = '' THEN
    v_pref := upper(NEW.metodo) || '-' || to_char(CURRENT_DATE, 'YYYYMMDD') || '-';
    PERFORM pg_advisory_xact_lock(hashtext('ref_pago'));
    SELECT COALESCE(MAX(right(referencia, 4)::int), 0) + 1 INTO v_sig
      FROM pagos WHERE referencia LIKE v_pref || '%';
    NEW.referencia := v_pref || lpad(v_sig::text, 4, '0');
  END IF;
  IF NEW.estado = 'completado' AND NEW.pagado_en IS NULL THEN
    NEW.pagado_en := now();
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_pagos_bi BEFORE INSERT ON pagos FOR EACH ROW EXECUTE FUNCTION fn_pagos_bi();

CREATE FUNCTION fn_pagos_ai() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_alumno INT;
BEGIN
  IF NEW.estado = 'completado' THEN
    UPDATE cargos SET estado = 'pagado' WHERE id = NEW.cargo_id RETURNING alumno_id INTO v_alumno;
    IF COALESCE((SELECT notif_pagos_tramites FROM ajustes_usuario WHERE usuario_id = v_alumno), TRUE) THEN
      INSERT INTO notificaciones (usuario_id, modulo, titulo, mensaje)
      VALUES (v_alumno, 'pagos', 'Pago registrado', 'Referencia ' || NEW.referencia);
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_pagos_ai AFTER INSERT ON pagos FOR EACH ROW EXECUTE FUNCTION fn_pagos_ai();

CREATE FUNCTION fn_pagos_bu() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF NEW.cargo_id <> OLD.cargo_id OR NEW.monto <> OLD.monto THEN
    RAISE EXCEPTION 'No se puede cambiar el cargo ni el monto de un pago';
  END IF;
  IF NEW.estado = 'completado' AND OLD.estado <> 'completado' AND NEW.pagado_en IS NULL THEN
    NEW.pagado_en := now();
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_pagos_bu BEFORE UPDATE ON pagos FOR EACH ROW EXECUTE FUNCTION fn_pagos_bu();

CREATE FUNCTION fn_pagos_au() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF NEW.estado = 'completado' AND OLD.estado <> 'completado' THEN
    UPDATE cargos SET estado = 'pagado' WHERE id = NEW.cargo_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_pagos_au AFTER UPDATE ON pagos FOR EACH ROW EXECUTE FUNCTION fn_pagos_au();

-- ---- 8.10 Préstamos de biblioteca ---------------------------------------
CREATE FUNCTION fn_prestamos_bi() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF NEW.fecha_limite IS NULL THEN
    NEW.fecha_limite := NEW.fecha_inicio + CASE WHEN NEW.tipo = 'prestamo' THEN 15 ELSE 2 END;
  END IF;
  IF NEW.estado = 'activo' THEN
    IF (SELECT COUNT(*) FROM prestamos WHERE alumno_id = NEW.alumno_id AND estado = 'activo') >= 3 THEN
      RAISE EXCEPTION 'Máximo 3 préstamos/reservas activos por alumno';
    END IF;
    IF (SELECT ejemplares_disponibles FROM libros WHERE id = NEW.libro_id) < 1 THEN
      RAISE EXCEPTION 'No hay ejemplares disponibles de este libro';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_prestamos_bi BEFORE INSERT ON prestamos FOR EACH ROW EXECUTE FUNCTION fn_prestamos_bi();

CREATE FUNCTION fn_prestamos_ai() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF NEW.estado = 'activo' THEN
    UPDATE libros SET ejemplares_disponibles = ejemplares_disponibles - 1 WHERE id = NEW.libro_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_prestamos_ai AFTER INSERT ON prestamos FOR EACH ROW EXECUTE FUNCTION fn_prestamos_ai();

CREATE FUNCTION fn_prestamos_bu() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  -- No se puede reactivar algo ya cerrado
  IF OLD.estado <> 'activo' AND NEW.estado = 'activo' THEN
    RAISE EXCEPTION 'Un préstamo cerrado no se puede reactivar';
  END IF;
  -- Renovación: solo préstamos activos, máximo 1 vez, +15 días
  IF NEW.renovaciones > OLD.renovaciones THEN
    IF OLD.tipo <> 'prestamo' OR OLD.estado <> 'activo' THEN
      RAISE EXCEPTION 'Solo se pueden renovar préstamos activos (no reservas)';
    END IF;
    IF OLD.renovaciones >= 1 THEN
      RAISE EXCEPTION 'Este préstamo ya se renovó una vez';
    END IF;
    NEW.fecha_limite := OLD.fecha_limite + 15;
  END IF;
  -- Reserva que se convierte en préstamo
  IF OLD.tipo = 'reserva' AND NEW.tipo = 'prestamo' AND OLD.estado = 'activo' THEN
    NEW.fecha_inicio := CURRENT_DATE;
    NEW.fecha_limite := CURRENT_DATE + 15;
  END IF;
  -- Al cerrar, se registra la fecha de devolución
  IF OLD.estado = 'activo' AND NEW.estado = 'devuelto' AND NEW.fecha_devolucion IS NULL THEN
    NEW.fecha_devolucion := CURRENT_DATE;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_prestamos_bu BEFORE UPDATE ON prestamos FOR EACH ROW EXECUTE FUNCTION fn_prestamos_bu();

CREATE FUNCTION fn_prestamos_au() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF OLD.estado = 'activo' AND NEW.estado IN ('devuelto','cancelado') THEN
    UPDATE libros SET ejemplares_disponibles = ejemplares_disponibles + 1 WHERE id = NEW.libro_id;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_prestamos_au AFTER UPDATE ON prestamos FOR EACH ROW EXECUTE FUNCTION fn_prestamos_au();

-- ---- 8.11 DriverUTSC --------------------------------------------------------
CREATE FUNCTION fn_reservas_valida() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
DECLARE v_conductor INT; v_borrada TIMESTAMPTZ; v_asientos INT; v_ocupados INT;
BEGIN
  IF NEW.estado = 'cancelada' THEN
    NEW.cancelada_en := COALESCE(NEW.cancelada_en, now());
    RETURN NEW;
  END IF;
  -- Solo se valida cuando la reserva queda activa
  SELECT conductor_id, deleted_at, asientos INTO v_conductor, v_borrada, v_asientos
    FROM rutas_driver WHERE id = NEW.ruta_id;
  IF v_borrada IS NOT NULL THEN
    RAISE EXCEPTION 'La ruta ya no está disponible';
  END IF;
  IF v_conductor = NEW.pasajero_id THEN
    RAISE EXCEPTION 'El conductor no puede reservar un lugar en su propia ruta';
  END IF;
  IF EXISTS (SELECT 1 FROM reservas_viaje
             WHERE ruta_id = NEW.ruta_id AND pasajero_id = NEW.pasajero_id
               AND estado = 'activa' AND (TG_OP = 'INSERT' OR id <> NEW.id)) THEN
    RAISE EXCEPTION 'Ya tienes una reserva activa en esta ruta';
  END IF;
  SELECT COUNT(*) INTO v_ocupados FROM reservas_viaje
   WHERE ruta_id = NEW.ruta_id AND estado = 'activa' AND (TG_OP = 'INSERT' OR id <> NEW.id);
  IF v_ocupados >= v_asientos THEN
    RAISE EXCEPTION 'No hay asientos disponibles en esa ruta';
  END IF;
  NEW.cancelada_en := NULL;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_reservas_bi BEFORE INSERT ON reservas_viaje FOR EACH ROW EXECUTE FUNCTION fn_reservas_valida();
CREATE TRIGGER trg_reservas_bu BEFORE UPDATE ON reservas_viaje FOR EACH ROW EXECUTE FUNCTION fn_reservas_valida();

CREATE FUNCTION fn_rutas_bu() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF NEW.asientos < (SELECT COUNT(*) FROM reservas_viaje WHERE ruta_id = NEW.id AND estado = 'activa') THEN
    RAISE EXCEPTION 'No puedes bajar los asientos por debajo de las reservas activas';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_rutas_bu BEFORE UPDATE ON rutas_driver FOR EACH ROW EXECUTE FUNCTION fn_rutas_bu();

CREATE FUNCTION fn_rutas_au() RETURNS trigger
LANGUAGE plpgsql SET search_path = utsc_portal, public AS $$
BEGIN
  IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
    UPDATE reservas_viaje SET estado = 'cancelada', cancelada_en = now()
     WHERE ruta_id = NEW.id AND estado = 'activa';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_rutas_au AFTER UPDATE ON rutas_driver FOR EACH ROW EXECUTE FUNCTION fn_rutas_au();

-- =====================================================================
-- Fin
-- =====================================================================
SELECT 'Esquema utsc_portal creado correctamente' AS resultado,
       (SELECT COUNT(*) FROM information_schema.tables
         WHERE table_schema = 'utsc_portal' AND table_type = 'BASE TABLE') AS tablas;
